# scheduler:
#   bucketsNum: 20
#   tryLockSeconds: 70
#   tryLockGapMilliSeconds: 100
#   successExpireSeconds: 130
# trigger:
#   zrangeGapSeconds: 1
#   workersNum: 10000
webserver:
   port: 8080
#migrator:
#   migrateStepMinutes: 60
#   migrateTryLockMinutes: 20
#   migrateSuccessExpireMinutes: 120
#   timerDetailCacheMinutes: 2
mysql:
   dsn:  "root:123456@tcp(127.0.0.1:3306)/timer?charset=utf8mb4&parseTime=True&loc=Local"
#   maxOpenConns: 100
#   maxIdleConns: 50
# pool:
#   size: 500000
#   expireSeconds: 30
#   nonBlocking: false
redis:
#   network: tcp
   address: "127.0.0.1:6379"
   password: ""
#   maxIdle: 2000
#   idleTimeout: 10
#   maxActive: 5000
#   wait: true